### ISSUE TITLE
GraphQl playground get js error

### ISSUE THREAD

**Issue by oranze** [nautilus/gateway#109] opened 2020-07-19 22:00 UTC
Good day.
I have a strange problem when clicking on "Schema" in right side of Playground.
Query's working fine, Docs tab also working fine. 
In browser 
`
react-dom.production.min.js:209 SyntaxError: Syntax Error: Unexpected } (3:1)
  1 | 
  2 |   
> 3 | }
    | ^
  4 | 
  5 | 
  6 |   
    at t.start.line (parser-graphql.js:1)
    at Object.parse (parser-graphql.js:1)
    at Object.parse (standalone.js:13721)
    at Hs (standalone.js:17145)
    at Ws (standalone.js:17381)
    at formatWithCursor (standalone.js:17397)
    at standalone.js:32917
    at Object.format (standalone.js:32926)
    at Object.t.prettify (utils.ts:22)
    at Object.l [as getSDL] (createSDL.ts:94)
es @ middleware.js:82
n.callback @ middleware.js:82
po @ middleware.js:82
os @ middleware.js:82
du @ middleware.js:82
t.unstable_runWithPriority @ middleware.js:90
Vi @ middleware.js:82
fu @ middleware.js:82
Zs @ middleware.js:82
(anonymous) @ middleware.js:82
t.unstable_runWithPriority @ middleware.js:90
Vi @ middleware.js:82
Gi @ middleware.js:82
Wi @ middleware.js:82
j @ middleware.js:82
Qt @ middleware.js:82
parser-graphql.js:1 Uncaught SyntaxError: Syntax Error: Unexpected } (3:1)
  1 | 
  2 |   
> 3 | }
    | ^
  4 | 
  5 | 
  6 |   
    at t.start.line (parser-graphql.js:1)
    at Object.parse (parser-graphql.js:1)
    at Object.parse (standalone.js:13721)
    at Hs (standalone.js:17145)
    at Ws (standalone.js:17381)
    at formatWithCursor (standalone.js:17397)
    at standalone.js:32917
    at Object.format (standalone.js:32926)
    at Object.t.prettify (utils.ts:22)
    at Object.l [as getSDL] (createSDL.ts:94)
t.start.line @ standalone.js:5278
parse @ standalone.js:5278
parse @ standalone.js:5278
Hs @ standalone.js:5278
Ws @ standalone.js:5278
formatWithCursor @ standalone.js:5278
(anonymous) @ standalone.js:5278
format @ standalone.js:5278
t.prettify @ middleware.js:27
l @ index.js:150
r.componentDidMount @ index.js:1
os @ middleware.js:82
du @ middleware.js:82
t.unstable_runWithPriority @ middleware.js:90
Vi @ middleware.js:82
fu @ middleware.js:82
Zs @ middleware.js:82
(anonymous) @ middleware.js:82
t.unstable_runWithPriority @ middleware.js:90
Vi @ middleware.js:82
Gi @ middleware.js:82
Wi @ middleware.js:82
j @ middleware.js:82
Qt @ middleware.js:82
react-dom.production.min.js:209 TypeError: Cannot read property 'off' of undefined
    at r.componentWillUnmount (SDLEditor.tsx:108)
    at react-dom.production.min.js:209
    at as (react-dom.production.min.js:214)
    at ls (react-dom.production.min.js:220)
    at du (react-dom.production.min.js:253)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Vi (react-dom.production.min.js:122)
    at fu (react-dom.production.min.js:248)
    at Zs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
es @ middleware.js:82
n.callback @ middleware.js:82
po @ middleware.js:82
os @ middleware.js:82
du @ middleware.js:82
t.unstable_runWithPriority @ middleware.js:90
Vi @ middleware.js:82
fu @ middleware.js:82
Zs @ middleware.js:82
(anonymous) @ middleware.js:82
t.unstable_runWithPriority @ middleware.js:90
Vi @ middleware.js:82
Gi @ middleware.js:82
Wi @ middleware.js:82
P @ middleware.js:82
z @ middleware.js:82
Xt @ middleware.js:82
$t @ middleware.js:82
t.unstable_runWithPriority @ middleware.js:90
Yt @ middleware.js:82
SDLEditor.tsx:108 Uncaught TypeError: Cannot read property 'off' of undefined
    at r.componentWillUnmount (SDLEditor.tsx:108)
    at react-dom.production.min.js:209
    at as (react-dom.production.min.js:214)
    at ls (react-dom.production.min.js:220)
    at du (react-dom.production.min.js:253)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Vi (react-dom.production.min.js:122)
    at fu (react-dom.production.min.js:248)
    at Zs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
r.componentWillUnmount @ index.js:1
(anonymous) @ middleware.js:82
as @ middleware.js:82
ls @ middleware.js:82
du @ middleware.js:82
t.unstable_runWithPriority @ middleware.js:90
Vi @ middleware.js:82
fu @ middleware.js:82
Zs @ middleware.js:82
(anonymous) @ middleware.js:82
t.unstable_runWithPriority @ middleware.js:90
Vi @ middleware.js:82
Gi @ middleware.js:82
Wi @ middleware.js:82
j @ middleware.js:82
Qt @ middleware.js:82
GraphQLEditor.tsx:587 Uncaught TypeError: Cannot read property 'getWidth' of null
    at GraphQLEditor.tsx:587
(anonymous) @ index.js:1
requestAnimationFrame (async)
e.setDocsWidth @ index.js:1
t.componentDidUpdate @ index.js:1
os @ middleware.js:82
du @ middleware.js:82
t.unstable_runWithPriority @ middleware.js:90
Vi @ middleware.js:82
fu @ middleware.js:82
Zs @ middleware.js:82
(anonymous) @ middleware.js:82
t.unstable_runWithPriority @ middleware.js:90
Vi @ middleware.js:82
Gi @ middleware.js:82
Wi @ middleware.js:82
j @ middleware.js:82
Qt @ middleware.js:82
`
gateway get schema only from one GraphQL controller.
Schema example:
`
schema {
    query: Query
}

type Race {
    id: ID!
    title: String!
    annex: String!
    number: Int!
    countryIso3: String!
    meeting: Meeting!
    scheduledTime: String!
    startedTime: String!
    signaledTime: String!
    distance: Int!
    meetingDate: String!
    type: String!
    subType: String!
}

type Meeting {
    id: ID!
    date: String!
    title: String!
    currency: String!
    autostart: Boolean!
    trackName: String!
}

type Query {
    race(id: ID!): Race
}
`

**Comment by AlecAivazis** [comment] 2020-11-10 19:35
Hey @oranze! Did you ever figure this out? If its still a problem i can try to find some time to take a look

**Comment by AlecAivazis** [comment] 2020-11-25 10:02
I am not able to reproduce this so I am going to close this issue. Please let me know if you run into it again.

**Closed by AlecAivazis** 2020-11-25 10:02 UTC
